### PR TITLE
Fix for paragraph multiline, only last paragraph is rendered correctly

### PR DESCRIPTION
**Pull request by Igoranze**
Hi,

Me agian.
There is another error which happens if you use multiple line blocks on paragraph.
If the input is:

```
p.. First one 'is'

ESCAPED "bad"

p.. Second one 'is'

ESCAPED "bad"

p.. Third one 'is'

ESCAPED "bad"

p.. Last one 'is'

ESCAPED "good"
```

The textile output is:

```
<p>First one &amp;#8216;is&amp;#8217;

&lt;span class=&quot;caps&quot;&gt;ESCAPED&lt;/span&gt; &amp;#8220;bad&amp;#8221;</p>

<p>Second one &amp;#8216;is&amp;#8217;

&lt;span class=&quot;caps&quot;&gt;ESCAPED&lt;/span&gt; &amp;#8220;bad&amp;#8221;</p>

<p>Third one &amp;#8216;is&amp;#8217;

&lt;span class=&quot;caps&quot;&gt;ESCAPED&lt;/span&gt; &amp;#8220;bad&amp;#8221;</p>

<p>Last one &#8216;is&#8217;

<span class="caps">ESCAPED</span> &#8220;good&#8221;</p>
```

Here we can see that only the last ```p..``` is escaped good.
Other (previous) paragraphs are double escaped:

```
&amp;#8216; (Double escaped, should be &#8216;)
&lt;span class=&quot;caps&quot;&gt;...&lt;/span&gt; (Double escaped, should be <span class="caps">ESCAPED</span>
```

Added test and fix.
The fix works as follows:

In utils.py
Added boolean ampersand.
If ampersand is True, add ampersand tuple. ```a = a + (('&', '&amp;'),)```

In core.py
on line 461:
Ampersand is set to false so that ampersand are not escaped

On line 508-509:
If the block tag is ```p``` then the ```graf()``` output is shelved (This fixes double escaping on the <span class='caps>...</span>'

### CODE REVIEW

**Comment by Igoranze** [comment]
Hmm... looks like there is more work for this fix... I will look into it tomorrow. Do you have any other ideas?

**Comment by ikirudennis** [comment]
Hello, and thanks again, @Igoranze for your time and attention.

I'll admit I haven't really looked at this, but if I had to guess it might be due to the difficulty of handling those extended blocks. By the way, I ran your test through txstyle.org, and the result doesn't match your expectation in the test. I always use that as a reference for output.

**Comment by Igoranze** [comment]
Hello @ikirudennis ,

I'm continuing with this bug development. I'm not quite sure why the tests are not passing? While on my local machine everything seems fine... It looks like the ```<span class='caps'>...</span>``` tags are not added here.

Also you said that the expected result does not mach that of txstyle.org. I suspect you mean the ```<p>...</p>``` on each new line. 
Have to look into that as well.

If you did manage to find a solution, please let me know.

**Comment by Igoranze** [comment]
Hi @ikirudennis,

I just pushed the last commit which fixes the <p>...</p> (output is the same as txstyle.org
Also there is no more double escaping on p.. multiline.

**Comment by ikirudennis** [comment]
Thanks again, @Igoranze! Do you have more bugs you are planning to fix? Should I wait a little bit to push a new release?

**Comment by Igoranze** [comment]
Hi @ikirudennis,

No, I do not have plans to fix other bugs so you can go ahead and release.
Thanks.

**Pull request merged**
